# Generated by Django 5.2.2 on 2025-06-05 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig', models.IntegerField()),
                ('descricao', models.CharField()),
                ('ni', models.CharField()),
                ('responsavel', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(choices=[('Temperatura', 'Temperatura'), ('Umidade', 'Umidade')], max_length=11)),
                ('mac_address', models.CharField(max_length=20)),
                ('unidade_med', models.CharField(choices=[('C', '°C'), ('%', '%')], max_length=2)),
                ('latitude', models.FloatField(max_length=20)),
                ('longitude', models.FloatField(max_length=20)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valor', models.FloatField()),
                ('timestamp', models.IntegerField()),
                ('ambientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ambientes')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sensores')),
            ],
        ),
    ]
