# Generated by Django 5.2.2 on 2025-06-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='Valor',
            new_name='valor',
        ),
        migrations.AlterField(
            model_name='sensores',
            name='unidade_med',
            field=models.CharField(choices=[('°C', '°C'), ('%', '%')], max_length=2),
        ),
    ]
