# Generated by Django 5.2.2 on 2025-06-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_valor_historico_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensores',
            name='sensor',
            field=models.CharField(choices=[('Temperatura', 'Temperatura'), ('Umidade', 'Umidade'), ('Luminosidade', 'Luminosidade'), ('Contador', 'Contador')], max_length=12),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='unidade_med',
            field=models.CharField(choices=[('°C', '°C'), ('%', '%'), ('lux', 'lux'), ('uni', 'uni')], max_length=3),
        ),
    ]
