# Generated by Django 5.2.2 on 2025-06-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_sensores_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensores',
            name='sensor',
            field=models.CharField(choices=[('Temperatura', 'Temperatura'), ('Umidade', 'Umidade'), ('Luminosidade', 'Luminosidade'), ('Contador', 'Contador')], max_length=12),
        ),
    ]
