# Generated by Django 5.2.2 on 2025-06-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_sensores_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensores',
            name='sensor',
            field=models.CharField(choices=[('temperatura', 'temperatura'), ('umidade', 'umidade'), ('luminosidade', 'luminosidade'), ('contador', 'contador')], max_length=12),
        ),
    ]
